import AppKit
import GhosttyKit
import os.log

let ghosttyLogger = Logger(subsystem: "com.iddogino.Relay", category: "ghostty")

/// Owns the single libghostty app instance, its configuration, and the
/// runtime callbacks. All libghostty C API use is confined to this file and
/// `TerminalSurfaceView`.
@MainActor
final class GhosttyRuntime {
    static let shared = GhosttyRuntime()

    private(set) var app: ghostty_app_t?
    private(set) var config: ghostty_config_t?
    private(set) var initError: String?

    private init() {
        // Ensure NSApp exists — this runs from App.init, before SwiftUI
        // creates the shared application.
        _ = NSApplication.shared

        if ghostty_init(UInt(CommandLine.argc), CommandLine.unsafeArgv) != GHOSTTY_SUCCESS {
            initError = "ghostty_init failed"
            return
        }

        guard let cfg = Self.loadConfig() else {
            initError = "Couldn't load the terminal configuration."
            return
        }
        self.config = cfg

        // IMPORTANT: these must be nonisolated function references, never
        // closures formed in this @MainActor context — libghostty invokes
        // them from its renderer/IO threads and a MainActor-inferred closure
        // would trip Swift's dynamic isolation assertion there.
        var runtimeConfig = ghostty_runtime_config_s(
            userdata: Unmanaged.passUnretained(self).toOpaque(),
            supports_selection_clipboard: false,
            wakeup_cb: ghosttyWakeupCallback,
            action_cb: ghosttyActionCallback,
            read_clipboard_cb: ghosttyReadClipboardCallback,
            confirm_read_clipboard_cb: ghosttyConfirmReadClipboardCallback,
            write_clipboard_cb: ghosttyWriteClipboardCallback,
            close_surface_cb: ghosttyCloseSurfaceCallback
        )

        guard let app = ghostty_app_new(&runtimeConfig, cfg) else {
            initError = "Couldn't start the terminal engine."
            return
        }
        self.app = app

        ghostty_app_set_focus(app, NSApp.isActive)
        syncColorScheme()

        let center = NotificationCenter.default
        center.addObserver(
            self, selector: #selector(applicationDidBecomeActive),
            name: NSApplication.didBecomeActiveNotification, object: nil)
        center.addObserver(
            self, selector: #selector(applicationDidResignActive),
            name: NSApplication.didResignActiveNotification, object: nil)
        center.addObserver(
            self, selector: #selector(keyboardSelectionDidChange),
            name: NSTextInputContext.keyboardSelectionDidChangeNotification, object: nil)

        appearanceObservation = NSApp.observe(\.effectiveAppearance) { [weak self] _, _ in
            Task { @MainActor in self?.syncColorScheme() }
        }
    }

    private var appearanceObservation: NSKeyValueObservation?

    // MARK: Configuration

    /// Loads the user's own Ghostty configuration (fonts, theme, keybinds, …)
    /// and then applies a small set of Relay-required overrides: an
    /// interoperable TERM so remote hosts never need Ghostty's terminfo, and
    /// lifecycle settings the app manages itself.
    private static func loadConfig() -> ghostty_config_t? {
        guard let cfg = ghostty_config_new() else { return nil }
        ghostty_config_load_default_files(cfg)

        let overrides = """
        # Generated by Relay on launch — do not edit (changes are overwritten).
        # Loaded after your own Ghostty config; only these keys are overridden.
        term = xterm-256color
        confirm-close-surface = false
        shell-integration = none
        """
        let supportDir = FileManager.default.urls(for: .applicationSupportDirectory, in: .userDomainMask)[0]
            .appendingPathComponent("Relay", isDirectory: true)
        let overridesURL = supportDir.appendingPathComponent("ghostty-overrides.conf")
        do {
            try FileManager.default.createDirectory(at: supportDir, withIntermediateDirectories: true)
            try overrides.write(to: overridesURL, atomically: true, encoding: .utf8)
            ghostty_config_load_file(cfg, overridesURL.path)
        } catch {
            ghosttyLogger.error("failed writing config overrides: \(error, privacy: .public)")
        }

        ghostty_config_finalize(cfg)

        let diagnostics = ghostty_config_diagnostics_count(cfg)
        for i in 0..<diagnostics {
            let diag = ghostty_config_get_diagnostic(cfg, i)
            if let message = diag.message {
                ghosttyLogger.warning("ghostty config: \(String(cString: message), privacy: .public)")
            }
        }
        return cfg
    }

    func reloadConfig() {
        guard let app else { return }
        guard let cfg = Self.loadConfig() else { return }
        if let old = config { ghostty_config_free(old) }
        config = cfg
        ghostty_app_update_config(app, cfg)
    }

    func tick() {
        guard let app else { return }
        ghostty_app_tick(app)
    }

    private func syncColorScheme() {
        guard let app else { return }
        let isDark = NSApp.effectiveAppearance.bestMatch(from: [.aqua, .darkAqua]) == .darkAqua
        ghostty_app_set_color_scheme(app, isDark ? GHOSTTY_COLOR_SCHEME_DARK : GHOSTTY_COLOR_SCHEME_LIGHT)
    }

    // MARK: App notifications

    @objc private func applicationDidBecomeActive(_ note: Notification) {
        guard let app else { return }
        ghostty_app_set_focus(app, true)
    }

    @objc private func applicationDidResignActive(_ note: Notification) {
        guard let app else { return }
        ghostty_app_set_focus(app, false)
    }

    @objc private func keyboardSelectionDidChange(_ note: Notification) {
        guard let app else { return }
        ghostty_app_keyboard_changed(app)
    }

    // MARK: C callbacks

    fileprivate nonisolated static func runtime(from userdata: UnsafeMutableRawPointer?) -> GhosttyRuntime? {
        guard let userdata else { return nil }
        return Unmanaged<GhosttyRuntime>.fromOpaque(userdata).takeUnretainedValue()
    }

    fileprivate nonisolated static func surfaceView(from userdata: UnsafeMutableRawPointer?) -> TerminalSurfaceView? {
        guard let userdata else { return nil }
        return Unmanaged<TerminalSurfaceView>.fromOpaque(userdata).takeUnretainedValue()
    }

    fileprivate nonisolated static func onWakeup(_ userdata: UnsafeMutableRawPointer?) {
        guard let runtime = runtime(from: userdata) else { return }
        // Wakeup may fire from any thread; ticks always run on main.
        DispatchQueue.main.async { runtime.tick() }
    }

    fileprivate nonisolated static func onAction(
        _ app: ghostty_app_t?,
        target: ghostty_target_s,
        action: ghostty_action_s
    ) -> Bool {
        let view: TerminalSurfaceView? = {
            guard target.tag == GHOSTTY_TARGET_SURFACE else { return nil }
            guard let surface = target.target.surface else { return nil }
            return surfaceView(from: ghostty_surface_userdata(surface))
        }()

        switch action.tag {
        case GHOSTTY_ACTION_SET_TITLE:
            guard let cTitle = action.action.set_title.title else { return false }
            let title = String(cString: cTitle)
            DispatchQueue.main.async { view?.terminalTitle = title }
            return true

        case GHOSTTY_ACTION_MOUSE_SHAPE:
            let shape = action.action.mouse_shape
            DispatchQueue.main.async { view?.setMouseShape(shape) }
            return true

        case GHOSTTY_ACTION_MOUSE_VISIBILITY:
            let visible = action.action.mouse_visibility == GHOSTTY_MOUSE_VISIBLE
            DispatchQueue.main.async { NSCursor.setHiddenUntilMouseMoves(!visible) }
            return true

        case GHOSTTY_ACTION_RING_BELL:
            DispatchQueue.main.async { NSSound.beep() }
            return true

        case GHOSTTY_ACTION_OPEN_URL:
            let openURL = action.action.open_url
            guard openURL.url != nil, openURL.len > 0 else { return false }
            let buffer = UnsafeBufferPointer(start: openURL.url, count: Int(openURL.len))
            guard let urlString = String(bytes: buffer.map { UInt8(bitPattern: $0) }, encoding: .utf8),
                  let url = URL(string: urlString),
                  let scheme = url.scheme?.lowercased(),
                  ["http", "https", "mailto", "file"].contains(scheme)
            else { return false }
            DispatchQueue.main.async { NSWorkspace.shared.open(url) }
            return true

        case GHOSTTY_ACTION_SHOW_CHILD_EXITED:
            // The SSH child exited. Suppress Ghostty's in-terminal message;
            // the attachment controller decides what happens next.
            DispatchQueue.main.async { view?.reportProcessExit() }
            return true

        case GHOSTTY_ACTION_RELOAD_CONFIG:
            DispatchQueue.main.async { GhosttyRuntime.shared.reloadConfig() }
            return true

        case GHOSTTY_ACTION_COLOR_CHANGE:
            let change = action.action.color_change
            guard change.kind == GHOSTTY_ACTION_COLOR_KIND_BACKGROUND else { return true }
            let color = NSColor(
                srgbRed: CGFloat(change.r) / 255,
                green: CGFloat(change.g) / 255,
                blue: CGFloat(change.b) / 255,
                alpha: 1)
            DispatchQueue.main.async { view?.terminalBackgroundColor = color }
            return true

        case GHOSTTY_ACTION_CELL_SIZE, GHOSTTY_ACTION_RENDERER_HEALTH,
             GHOSTTY_ACTION_SIZE_LIMIT, GHOSTTY_ACTION_INITIAL_SIZE,
             GHOSTTY_ACTION_PWD, GHOSTTY_ACTION_SCROLLBAR,
             GHOSTTY_ACTION_PROGRESS_REPORT, GHOSTTY_ACTION_KEY_SEQUENCE,
             GHOSTTY_ACTION_KEY_TABLE, GHOSTTY_ACTION_CONFIG_CHANGE,
             GHOSTTY_ACTION_QUIT_TIMER, GHOSTTY_ACTION_COMMAND_FINISHED:
            // Understood and intentionally ignored.
            return true

        default:
            // Unsupported in a single-surface embedding (splits, tabs, …).
            return false
        }
    }

    fileprivate nonisolated static func onReadClipboard(
        _ userdata: UnsafeMutableRawPointer?,
        location: ghostty_clipboard_e,
        state: UnsafeMutableRawPointer?
    ) -> Bool {
        guard location == GHOSTTY_CLIPBOARD_STANDARD else { return false }
        guard let view = surfaceView(from: userdata) else { return false }
        nonisolated(unsafe) let statePointer = state

        let complete = { @MainActor in
            guard let surface = view.surface else { return }
            guard let string = NSPasteboard.general.string(forType: .string) else {
                // Nothing text-like on the pasteboard; complete with empty.
                ghostty_surface_complete_clipboard_request(surface, "", statePointer, false)
                return
            }
            string.withCString { pointer in
                ghostty_surface_complete_clipboard_request(surface, pointer, statePointer, false)
            }
        }
        if Thread.isMainThread {
            MainActor.assumeIsolated(complete)
        } else {
            DispatchQueue.main.async { complete() }
        }
        return true
    }

    fileprivate nonisolated static func onConfirmReadClipboard(
        _ userdata: UnsafeMutableRawPointer?,
        string: UnsafePointer<CChar>?,
        state: UnsafeMutableRawPointer?,
        request: ghostty_clipboard_request_e
    ) {
        guard let view = surfaceView(from: userdata) else { return }
        let contents = string.map { String(cString: $0) } ?? ""
        nonisolated(unsafe) let statePointer = state
        let isPaste = request == GHOSTTY_CLIPBOARD_REQUEST_PASTE

        DispatchQueue.main.async {
            view.confirmClipboard(contents: contents, isPaste: isPaste) { confirmed in
                guard let surface = view.surface else { return }
                contents.withCString { pointer in
                    ghostty_surface_complete_clipboard_request(surface, pointer, statePointer, confirmed)
                }
            }
        }
    }

    fileprivate nonisolated static func onWriteClipboard(
        _ userdata: UnsafeMutableRawPointer?,
        location: ghostty_clipboard_e,
        content: UnsafePointer<ghostty_clipboard_content_s>?,
        len: Int,
        confirm: Bool
    ) {
        guard location == GHOSTTY_CLIPBOARD_STANDARD else { return }
        guard let content, len > 0 else { return }
        // Find the plain-text entry.
        var text: String?
        for i in 0..<len {
            let item = content[i]
            guard let mime = item.mime, let data = item.data else { continue }
            if String(cString: mime) == "text/plain" {
                text = String(cString: data)
                break
            }
        }
        guard let text else { return }

        let view = surfaceView(from: userdata)
        DispatchQueue.main.async {
            if confirm, let view {
                view.confirmClipboard(contents: text, isPaste: false) { confirmed in
                    guard confirmed else { return }
                    NSPasteboard.general.declareTypes([.string], owner: nil)
                    NSPasteboard.general.setString(text, forType: .string)
                }
            } else {
                NSPasteboard.general.declareTypes([.string], owner: nil)
                NSPasteboard.general.setString(text, forType: .string)
            }
        }
    }

    fileprivate nonisolated static func onCloseSurface(_ userdata: UnsafeMutableRawPointer?, processAlive: Bool) {
        guard let view = surfaceView(from: userdata) else { return }
        DispatchQueue.main.async { view.reportProcessExit() }
    }
}


// MARK: - C callback thunks
//
// Top-level functions so they convert to C function pointers with no actor
// isolation; libghostty calls them from arbitrary threads.

private func ghosttyWakeupCallback(_ userdata: UnsafeMutableRawPointer?) {
    GhosttyRuntime.onWakeup(userdata)
}

private func ghosttyActionCallback(
    _ app: ghostty_app_t?,
    _ target: ghostty_target_s,
    _ action: ghostty_action_s
) -> Bool {
    GhosttyRuntime.onAction(app, target: target, action: action)
}

private func ghosttyReadClipboardCallback(
    _ userdata: UnsafeMutableRawPointer?,
    _ location: ghostty_clipboard_e,
    _ state: UnsafeMutableRawPointer?
) -> Bool {
    GhosttyRuntime.onReadClipboard(userdata, location: location, state: state)
}

private func ghosttyConfirmReadClipboardCallback(
    _ userdata: UnsafeMutableRawPointer?,
    _ string: UnsafePointer<CChar>?,
    _ state: UnsafeMutableRawPointer?,
    _ request: ghostty_clipboard_request_e
) {
    GhosttyRuntime.onConfirmReadClipboard(userdata, string: string, state: state, request: request)
}

private func ghosttyWriteClipboardCallback(
    _ userdata: UnsafeMutableRawPointer?,
    _ location: ghostty_clipboard_e,
    _ content: UnsafePointer<ghostty_clipboard_content_s>?,
    _ len: Int,
    _ confirm: Bool
) {
    GhosttyRuntime.onWriteClipboard(userdata, location: location, content: content, len: len, confirm: confirm)
}

private func ghosttyCloseSurfaceCallback(_ userdata: UnsafeMutableRawPointer?, _ processAlive: Bool) {
    GhosttyRuntime.onCloseSurface(userdata, processAlive: processAlive)
}
